// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DailyTaskMaker.Infrastructure.Models;

public partial class DailyTaskMakerDbContext : DbContext
{
    public DailyTaskMakerDbContext(DbContextOptions<DailyTaskMakerDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ExpenseTrackerCategory> ExpenseTrackerCategories { get; set; }

    public virtual DbSet<UserDetail> UserDetails { get; set; }

    public virtual DbSet<UserExpenseTracker> UserExpenseTrackers { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<UserRoleMapping> UserRoleMappings { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ExpenseTrackerCategory>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__ExpenseT__19093A0BAD3A5504");

            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<UserDetail>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__UserDeta__1788CC4C5892D7A1");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<UserExpenseTracker>(entity =>
        {
            entity.HasKey(e => e.UserExpenseTrackerId).HasName("PK__UserExpe__3D3AE14442697F81");

            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Category).WithMany(p => p.UserExpenseTrackers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserExpenseTracker_CategoryId");

            entity.HasOne(d => d.User).WithMany(p => p.UserExpenseTrackers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserExpenseTracker_UserId");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => e.UserRoleId).HasName("PK__UserRole__3D978A55AF137A02");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<UserRoleMapping>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserRole__3214EC07801FE77D");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoleMappings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoleMapping_userId");

            entity.HasOne(d => d.UserRole).WithMany(p => p.UserRoleMappings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoleMapping_UserRoleID");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}