// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DailyTaskMaker.Infrastructure.Models;

[Table("ExpenseTrackerCategory")]
public partial class ExpenseTrackerCategory
{
    [Key]
    public int CategoryId { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string CategoryName { get; set; }

    public bool? IsActive { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<UserExpenseTracker> UserExpenseTrackers { get; set; } = new List<UserExpenseTracker>();
}