// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DailyTaskMaker.Infrastructure.Models;

[Table("UserDetail")]
public partial class UserDetail
{
    [Key]
    public int UserId { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string SurName { get; set; }

    [Required]
    [Column("EmailID")]
    [StringLength(500)]
    [Unicode(false)]
    public string EmailId { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string MobileNumber { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string DisplayName { get; set; }

    public bool? IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string UpdatedBy { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<UserExpenseTracker> UserExpenseTrackers { get; set; } = new List<UserExpenseTracker>();

    [InverseProperty("User")]
    public virtual ICollection<UserRoleMapping> UserRoleMappings { get; set; } = new List<UserRoleMapping>();
}