// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DailyTaskMaker.Infrastructure.Models;

[Table("UserExpenseTracker")]
public partial class UserExpenseTracker
{
    [Key]
    public int UserExpenseTrackerId { get; set; }

    public int UserId { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string Description { get; set; }

    public int CategoryId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ExpenseDate { get; set; }

    public int Price { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string UpdatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("UserExpenseTrackers")]
    public virtual ExpenseTrackerCategory Category { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserExpenseTrackers")]
    public virtual UserDetail User { get; set; }
}