// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DailyTaskMaker.Infrastructure.Models;

[Table("UserRoleMapping")]
public partial class UserRoleMapping
{
    [Key]
    public int Id { get; set; }

    public int UserId { get; set; }

    [Column("UserRoleID")]
    public int UserRoleId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string UpdatedBy { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserRoleMappings")]
    public virtual UserDetail User { get; set; }

    [ForeignKey("UserRoleId")]
    [InverseProperty("UserRoleMappings")]
    public virtual UserRole UserRole { get; set; }
}